//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Login.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserInfo
    {
        public int U_NO { get; set; }
        public Nullable<int> U_JobNO { get; set; }
        public string U_LoginName { get; set; }
        public string U_Password { get; set; }
        public string U_Dept { get; set; }
        public string U_Name { get; set; }
        public string U_Sex { get; set; }
        public Nullable<int> U_Age { get; set; }
        public string U_Telephone { get; set; }
        public Nullable<int> U_Role { get; set; }
    }
}
